### ISSUE TITLE
"torch._C.Value has no attribute 'uniqueName'" Error running with PyTorch 1.2

### ISSUE THREAD

**Issue by cted18** [waleedka/hiddenlayer#51]
PyTorch Version: '1.2.0a'
Python: 3.6.8
`
Exception has occurred: AttributeError
'torch._C.Value' object has no attribute 'uniqueName'
  File "hiddenlayer/hiddenlayer/pytorch_builder.py", line 45, in <listcomp>
    return node.scopeName() + "/outputs/" + "/".join([o.uniqueName() for o in node.outputs()])
  File "hiddenlayer/hiddenlayer/pytorch_builder.py", line 45, in pytorch_id
    return node.scopeName() + "/outputs/" + "/".join([o.uniqueName() for o in node.outputs()])
  File "hiddenlayer/hiddenlayer/pytorch_builder.py", line 90, in import_graph
    hl_node = Node(uid=pytorch_id(torch_node), name=None, op=op,
  File "hiddenlayer/hiddenlayer/graph.py", line 143, in build_graph
    import_graph(g, model, args)
  File "visualizer.py", line 20, in <module>
    graph = hl.build_graph(model, input)
`

Works well with older version of PyTorch (0.4.1).

**Comment by phillies** [comment]
I can confirm that the PR fixes the issue with pytorch 1.2.0, @waleedka please merge and build new pip package

**Comment by emjay73** [comment]
fyi, I changed UniqueName() to debugName()
ref :https://github.com/microsoft/human-pose-estimation.pytorch/issues/122#issuecomment-532984020

**Comment by g13e** [comment]
any plan to merge this anytime soon?
