### PR TITLE
Fix deprecated torch method call to uniqueName

### LINKED ISSUE #51: "torch._C.Value has no attribute 'uniqueName'" Error running with PyTorch 1.2
PyTorch Version: '1.2.0a'
Python: 3.6.8
`
Exception has occurred: AttributeError
'torch._C.Value' object has no attribute 'uniqueName'
  File "hiddenlayer/hiddenlayer/pytorch_builder.py", line 45, in <listcomp>
    return node.scopeName() + "/outputs/" + "/".join([o.uniqueName() for o in node.outputs()])
  File "hiddenlayer/hiddenlayer/pytorch_builder.py", line 45, in pytorch_id
    return node.scopeName() + "/outputs/" + "/".join([o.uniqueName() for o in node.outputs()])
  File "hiddenlayer/hiddenlayer/pytorch_builder.py", line 90, in import_graph
    hl_node = Node(uid=pytorch_id(torch_node), name=None, op=op,
  File "hiddenlayer/hiddenlayer/graph.py", line 143, in build_graph
    import_graph(g, model, args)
  File "visualizer.py", line 20, in <module>
    graph = hl.build_graph(model, input)
`

Works well with older version of PyTorch (0.4.1).

### PR DESCRIPTION
**Pull request by jccurtis**
Fixes #51

`hiddenlayer==0.2.0` is not compatible with `torch==1.2.0` (which is currently the latest installed with `pip3 install torchvision` and overrides an existing/lower `torch` version.) This PR is a simple patch which uses the `unique()` method of a `torch._C.Value` instead of the `uniqueName` method which is missing in `torch==1.2.0`.

### CODE REVIEW

**Comment by waleedka** [comment]
Thank you so much for the fix. And, apologies for the long delay. It's merged.
